services:
  db:
    image: postgres:16
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
