
create table if not exists recipes
(
    id bigint generated by default as identity not null primary key,
    uuid uuid not null,
    title text not null,
    ingredients text not null,
    instructions text not null
);
