services:
  db:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_DB: usersDb
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePassword
