###
# POST User
###

POST {{host}}/users
Accept: application/json
Content-Type: application/json

{ "username": "admin", "email": "admin@example.com" }

###

###
# GET User Details
###

GET {{host}}/users/1
Accept: application/json

###

###
# GET All Users Details
###

GET {{host}}/users
Accept: text/event-stream
